### ISSUE TITLE
Pulling gives unauthorized error

### ISSUE THREAD

**Issue by IvoMerchiers** [kunickiaj/kudu-docker#7]
Calling

 `docker pull kunickiaj/kudu`
or 
`docker run --rm -it --link kududocker_kudu-tserver_1:kudu_tserver -e KUDU_TSERVER=kudu_tserver kunickiaj/kudu cli status
`

both result in an authorization error
```
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/kunickiaj/kudu/manifests/latest: unauthorized: incorrect username or password
```

This has been tested both on windows and mac.

**Comment by IvoMerchiers** [comment]
Using 
`Docker logout`
resolved this issue.

It seems weird that this is a problem, could this be due to some settings on the docker repo?

**Comment by kunickiaj** [comment]
Don't think so. Docker repo is public.
